"""Initial tables

Revision ID: 508a32776b0c
Revises: 7faf594f4bd0
Create Date: 2025-04-17 21:41:44.988058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '508a32776b0c'
down_revision: Union[str, None] = '7faf594f4bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('migration')
    op.drop_table('piccolo_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piccolo_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='piccolo_user_pkey'),
    sa.UniqueConstraint('email', name='piccolo_user_email_key'),
    sa.UniqueConstraint('username', name='piccolo_user_username_key')
    )
    op.create_table('migration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('ran_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_pkey')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP + '01:00:00'::interval)"), autoincrement=False, nullable=False),
    sa.Column('max_expiry_date', postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP + '7 days'::interval)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    # ### end Alembic commands ###
