"""add new fields to Company

Revision ID: d3913156a90f
Revises: 
Create Date: 2025-04-30 00:44:08.811888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3913156a90f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('display_number', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('zapi_instance_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('zapi_token', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'phone_number_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'ai_prompt',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('companies', 'whatsapp_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('companies', 'webhook_secret',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('companies_phone_number_id_key', 'companies', type_='unique')
    op.drop_index('ix_companies_id', table_name='companies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_companies_id', 'companies', ['id'], unique=False)
    op.create_unique_constraint('companies_phone_number_id_key', 'companies', ['phone_number_id'])
    op.alter_column('companies', 'webhook_secret',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('companies', 'whatsapp_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('companies', 'ai_prompt',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('companies', 'phone_number_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'active')
    op.drop_column('companies', 'zapi_token')
    op.drop_column('companies', 'zapi_instance_id')
    op.drop_column('companies', 'provider')
    op.drop_column('companies', 'display_number')
    # ### end Alembic commands ###
